export const academicsPermissions = {
  curricula: {
    read: "academics.curriculum.read",
    create: "academics.curriculum.create",
    update: "academics.curriculum.update",
    deactivate: "academics.curriculum.deactivate",
  },
  academicOfferings: {
    read: "academics.academic-offering.read",
    create: "academics.academic-offering.create",
    update: "academics.academic-offering.update",
    deactivate: "academics.academic-offering.deactivate",
  },
  programs: {
    read: "academics.programs.read",
    create: "academics.programs.create",
    update: "academics.programs.update",
    deactivate: "academics.programs.deactivate",
  },
  classes: {
    read: "academics.classes.read",
    create: "academics.classes.create",
    update: "academics.classes.update",
    deactivate: "academics.classes.deactivate",
  },
  sections: {
    read: "academics.sections.read",
    create: "academics.sections.create",
    update: "academics.sections.update",
    deactivate: "academics.sections.deactivate",
  },
  subjects: {
    read: "academics.subjects.read",
    create: "academics.subjects.create",
    update: "academics.subjects.update",
    deactivate: "academics.subjects.deactivate",
  },
  subjectCatalogue: {
    read: "academics.subject-catalogue.read",
    create: "academics.subject-catalogue.create",
    update: "academics.subject-catalogue.update",
    deactivate: "academics.subject-catalogue.deactivate",
  },
  curriculumSubjects: {
    read: "academics.curriculum-subject.read",
    create: "academics.curriculum-subject.create",
    update: "academics.curriculum-subject.update",
    deactivate: "academics.curriculum-subject.deactivate",
  },
  subjectComponents: {
    read: "academics.subject-component.read",
    create: "academics.subject-component.create",
    deactivate: "academics.subject-component.deactivate",
  },
  subjectPlans: {
    read: "academics.subject-plan.read",
    create: "academics.subject-plan.create",
    activate: "academics.subject-plan.activate",
  },
  learningDelivery: {
    sectionSubjectExceptionManage: "academics.section-subject-exception.manage",
    sectionSubjectExceptionRead: "academics.section-subject-exception.read",
    subjectChoiceGroupManage: "academics.subject-choice-group.manage",
    subjectChoiceGroupRead: "academics.subject-choice-group.read",
    studentSubjectChoiceManage: "academics.student-subject-choice.manage",
    studentSubjectChoiceRead: "academics.student-subject-choice.read",
    teachingGroupManage: "academics.teaching-group.manage",
    teachingGroupRead: "academics.teaching-group.read",
    subjectOfferingManage: "academics.subject-offering.manage",
    subjectOfferingRead: "academics.subject-offering.read",
    timetableManage: "academics.timetable.manage",
    timetableRead: "academics.timetable.read",
    timetableValidate: "academics.timetable.validate",
    timetablePublish: "academics.timetable.publish",
  },
  facultyPlanning: {
    read: "academics.faculty-planning.read",
    manage: "academics.faculty-planning.manage",
  },
  students: {
    read: "academics.student.read",
    create: "academics.student.create",
    update: "academics.student.update",
    enroll: "academics.enrollment.create",
    transferRead: "academics.campus-transfer.read",
    transferCreate: "academics.campus-transfer.create",
    transferApprove: "academics.campus-transfer.approve",
    transferCancel: "academics.campus-transfer.cancel",
  },
  teachingAssignments: {
    read: "academics.teaching-assignment.read",
    manage: "academics.teaching-assignment.manage",
  },
  studentDocuments: {
    read: "academics.student-document.read",
    issue: "academics.student-document.issue",
    revoke: "academics.student-document.revoke",
  },
  studentNotes: {
    read: "academics.student-note.read",
    create: "academics.student-note.create",
    update: "academics.student-note.update",
  },
} as const;
