import { ConflictError } from "@school-erp/errors";
import { createMongoCollectionAdapter, getCollection, type CollectionAdapter, type MongoEnvLike } from "@school-erp/mongodb";
import { DEFAULT_NUMBERING_POLICIES, type NumberingPolicyInput, type NumberingPolicyRecord, type NumberingStream } from "./numbering.model";
interface NumberingDocument extends NumberingPolicyRecord { _id: string; }
export interface NumberingRepository { list(tenantId:string):Promise<NumberingPolicyRecord[]>; upsert(tenantId:string,input:NumberingPolicyInput):Promise<NumberingPolicyRecord>; }
function record(tenantId:string,input:NumberingPolicyInput):NumberingPolicyRecord{const now=new Date();return{id:`numbering_${tenantId}_${input.stream}`.replace(/[^a-zA-Z0-9_-]/g,"_"),tenantId,...input,nextNumber:1,issuedCount:0,createdAt:now,updatedAt:now};}
function clone(v:NumberingPolicyRecord){return{...v,createdAt:new Date(v.createdAt),updatedAt:new Date(v.updatedAt)};}
export class InMemoryNumberingRepository implements NumberingRepository { private data=new Map<string,NumberingPolicyRecord>();async list(tenantId:string){return[...this.data.values()].filter(v=>v.tenantId===tenantId).map(clone);}async upsert(tenantId:string,input:NumberingPolicyInput){const key=`${tenantId}:${input.stream}`;const old=this.data.get(key);if(old&&old.issuedCount>0&&(old.scope!==input.scope||old.reset!==input.reset))throw new ConflictError("scope and reset cannot change after numbers have been issued");const next=old?{...old,...input,updatedAt:new Date()}:record(tenantId,input);this.data.set(key,next);return clone(next);}}
export class MongoNumberingRepository implements NumberingRepository { constructor(private collection:CollectionAdapter<NumberingDocument>){}async list(tenantId:string){return(await this.collection.findMany({tenantId})).map(({_id,...v})=>clone({...v,id:v.id||_id}));}async upsert(tenantId:string,input:NumberingPolicyInput){const existing=await this.collection.findOne({tenantId,stream:input.stream});if(existing&&existing.issuedCount>0&&(existing.scope!==input.scope||existing.reset!==input.reset))throw new ConflictError("scope and reset cannot change after numbers have been issued");const value=existing?{...existing,...input,updatedAt:new Date()}:{...record(tenantId,input),_id:`numbering_${tenantId}_${input.stream}`};if(existing)await this.collection.replaceOne({_id:existing._id,tenantId},value);else await this.collection.insertOne(value);const{_id,...result}=value;return clone({...result,id:result.id||_id});}}
function env():MongoEnvLike{return(globalThis as unknown as{process?:{env?:MongoEnvLike}}).process?.env??{};}let singleton:Promise<NumberingRepository>|undefined;export async function createNumberingRepository(e:MongoEnvLike=env()){if(!e.MONGODB_URI&&!e.MONGODB_URI_DEV&&!e.MONGODB_URI_PROD&&!e.MONGODB_URI_TEST)return new InMemoryNumberingRepository();const c=await getCollection<NumberingDocument>("settings_numbering_policies",e);await c.createIndex({tenantId:1,stream:1},{unique:true});return new MongoNumberingRepository(createMongoCollectionAdapter(c));}async function repo(){return singleton??=createNumberingRepository();}
export const numberingRepository:NumberingRepository={list:async(...a)=>(await repo()).list(...a),upsert:async(...a)=>(await repo()).upsert(...a)};
export async function ensureDefaultNumberingPolicies(repository:NumberingRepository,tenantId:string){const existing=await repository.list(tenantId);const byStream=new Map(existing.map(v=>[v.stream,v]));for(const policy of DEFAULT_NUMBERING_POLICIES){const current=byStream.get(policy.stream);if(!current)await repository.upsert(tenantId,policy);else if(!current.format)await repository.upsert(tenantId,{...policy,name:current.name,prefix:current.prefix,separator:current.separator,padding:current.padding,scope:current.scope,reset:current.reset,active:current.active});}return repository.list(tenantId);}
