import test from "node:test";
import assert from "node:assert/strict";
import { createMockRequestContext } from "@school-erp/test-utils";
import { InMemoryAcademicYearRepository } from "../academic-years.repository";
import { activateAcademicYear, closeAcademicYear, createAcademicYear, reopenAcademicYear } from "../academic-years.service";

function context(){return createMockRequestContext({tenantContext:{tenantId:"tenant-1"}as any,authContext:{user:{id:"user-1",permissions:["settings.academicyears.create","settings.academicyears.activate","settings.academicyears.close","settings.academicyears.reopen"]},source:"request",authenticatedAt:new Date()}as any})as any;}
test("first year is active and later years start as drafts",async()=>{const repository=new InMemoryAcademicYearRepository();const first=await createAcademicYear(context(),{name:"2026-27",startDate:"2026-06-01",endDate:"2027-05-31"},{repository});const second=await createAcademicYear(context(),{name:"2027-28",startDate:"2027-06-01",endDate:"2028-05-31"},{repository});assert.equal(first.status,"ACTIVE");assert.equal(second.status,"DRAFT");});
test("activating a draft closes the previous current year",async()=>{const repository=new InMemoryAcademicYearRepository();const first=await createAcademicYear(context(),{name:"2026-27",startDate:"2026-06-01",endDate:"2027-05-31"},{repository});const second=await createAcademicYear(context(),{name:"2027-28",startDate:"2027-06-01",endDate:"2028-05-31"},{repository});await activateAcademicYear(context(),second.id,{repository});assert.equal((await repository.getById("tenant-1",first.id))?.status,"CLOSED");assert.equal((await repository.getById("tenant-1",second.id))?.status,"ACTIVE");});
test("closing and reopening require a recorded reason",async()=>{const repository=new InMemoryAcademicYearRepository();const year=await createAcademicYear(context(),{name:"2026-27",startDate:"2026-06-01",endDate:"2027-05-31"},{repository});await assert.rejects(()=>closeAcademicYear(context(),year.id,"no",{repository}),/at least 5/);const closed=await closeAcademicYear(context(),year.id,"Year-end review complete",{repository});assert.equal(closed?.status,"CLOSED");const reopened=await reopenAcademicYear(context(),year.id,"Correction required",{repository});assert.equal(reopened?.status,"DRAFT");});
