import type { RequestContext } from "@school-erp/api";
import { normalizePermissions } from "@school-erp/auth";
import { ForbiddenError, toErrorResponse } from "@school-erp/errors";
import { academicsPermissions } from "../permissions";
import { studentDocumentRepository } from "../modules/student-documents/student-documents.repository";
import { getStudentDocumentBranding } from "../modules/student-documents/student-document-branding";
import { renderStudentDocumentPdf } from "../modules/student-documents/student-document-pdf";
import { hydrateAcademicsRuntimeConfig } from "./runtime-config";
interface Event{pathParameters?:{documentId?:string};requestContext?:{requestId?:string;authorizer?:{jwt?:{claims?:Record<string,unknown>}}}}
const claim=(c:Record<string,unknown>,n:string)=>typeof c[n]==="string"?(c[n] as string).trim():undefined;const b64=(bytes:Uint8Array)=>{let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)};
export async function handler(event:Event){const traceId=event.requestContext?.requestId;try{await hydrateAcademicsRuntimeConfig();const claims=event.requestContext?.authorizer?.jwt?.claims??{},userId=claim(claims,"sub"),tenantId=claim(claims,"custom:tenantId"),id=event.pathParameters?.documentId?.trim();if(!userId||!tenantId||!id)throw new ForbiddenError("authenticated tenant identity and documentId are required");const role=claim(claims,"custom:role")??claim(claims,"cognito:groups");const permissions=normalizePermissions([...(role?.includes("TENANT_ADMIN")?[academicsPermissions.studentDocuments.read]:[]),...normalizePermissions(claims["custom:permissions"]??claims.permissions)]);const ctx:RequestContext={requestId:traceId??`document_${crypto.randomUUID()}`,method:"GET",path:"/v1/student-documents/:documentId/pdf",headers:{},query:{},body:undefined,params:{documentId:id},tenantContext:{tenantId,source:"jwt-claims",resolvedAt:new Date()},authContext:{source:"jwt-claims",authenticatedAt:new Date(),user:{id:userId,role,permissions,source:"jwt-claims"}}};void ctx;const record=await(await studentDocumentRepository()).getById(tenantId,id);if(!record||record.status!=="ISSUED")throw new ForbiddenError("issued student document is not available");if(!permissions.includes(academicsPermissions.studentDocuments.read))throw new ForbiddenError("student document read permission is required");const branding=await getStudentDocumentBranding(tenantId,record.campusId,record.academicYearId,record.classId,record.sectionId);const pdf=await renderStudentDocumentPdf(record,branding);return{statusCode:200,headers:{"content-type":"application/pdf","content-disposition":`attachment; filename=\"${record.documentNumber.replaceAll("/","-")}.pdf\"`,"cache-control":"private, no-store"},body:b64(pdf),isBase64Encoded:true};}catch(error){const response=toErrorResponse(error,traceId);return{statusCode:response.statusCode,headers:{"content-type":"application/json"},body:JSON.stringify(response.body)}}}
