export type AccessScopeType = "TENANT" | "CAMPUS" | "PROGRAM" | "CLASS" | "SECTION" | "ASSIGNED_ONLY";
export interface AccessScope { scopeType: AccessScopeType; campusIds?: string[]; programIds?: string[]; classIds?: string[]; sectionIds?: string[]; }
export interface UserRoleAssignment { id:string;tenantId:string;userId:string;roleId:string;scope:AccessScope;isActive:boolean;createdAt:Date;updatedAt:Date; }
export interface AssignmentPageFilter { userId?:string;userIds?:string[];roleId?:string;isActive?:boolean;page?:number;pageSize?:number }
export interface AssignmentPage { items:UserRoleAssignment[];page:number;pageSize:number;total:number;totalPages:number }
export interface RolePermissionBinding { id:string;tenantId:string;roleId:string;permission:string;createdAt:Date;updatedAt:Date; }
export interface PermissionCatalogItem { code:string;domain:string;resource:string;action:string;label:string; }
const PERMISSION_ROWS = [
  ["settings.institution.read","Settings","Institution","Read"],["settings.institution.update","Settings","Institution","Update"],
  ["settings.campuses.read","Settings","Campuses","Read"],["settings.campuses.create","Settings","Campuses","Create"],["settings.campuses.update","Settings","Campuses","Update"],
  ["settings.academicYears.read","Settings","Academic years","Read"],["settings.academicYears.create","Settings","Academic years","Create"],["settings.academicYears.update","Settings","Academic years","Update"],["settings.academicYears.activate","Settings","Academic years","Activate"],
  ["settings.templates.read","Settings","Templates","Read"],["settings.templates.create","Settings","Templates","Create"],["settings.templates.update","Settings","Templates","Update"],["settings.templates.publish","Settings","Templates","Publish"],
  ["settings.numbering.read","Settings","Numbering","Read"],["settings.numbering.manage","Settings","Numbering","Manage"],["settings.notifications.read","Settings","Notifications","Read"],["settings.notifications.update","Settings","Notifications","Update"],
  ["identity.user.read","Identity","Users","Read"],["identity.user.create","Identity","Users","Create"],["identity.user.update","Identity","Users","Update"],["identity.user.deactivate","Identity","Users","Deactivate"],["identity.user.invite","Identity","Users","Invite"],
  ["identity.role.read","Identity","Roles","Read"],["identity.role.create","Identity","Roles","Create"],["identity.role.update","Identity","Roles","Update"],["identity.role.assign","Identity","Roles","Assign"],["identity.permissions.read","Identity","Permissions","Read"],["identity.permissions.assign","Identity","Permissions","Assign"],
  ["identity.employee.read","Identity","Employees","Read"],["identity.employee.create","Identity","Employees","Create"],["identity.employee.update","Identity","Employees","Update"],["identity.employee.end","Identity","Employees","End employment"],["identity.employee.invite","Identity","Employees","Invite"],["identity.employee.disableLogin","Identity","Employees","Disable login"],
  ["academics.structure.read","Academics","Structure","Read"],["academics.structure.manage","Academics","Structure","Manage"],["academics.student.read","Academics","Students","Read"],["academics.student.create","Academics","Students","Create"],["academics.student.update","Academics","Students","Update"],
  ["academics.campus-transfer.read","Academics","Campus transfers","Read"],["academics.campus-transfer.create","Academics","Campus transfers","Create"],["academics.campus-transfer.approve","Academics","Campus transfers","Approve"],["academics.campus-transfer.cancel","Academics","Campus transfers","Cancel"],
  ["admissions.enquiry.read","Admissions","Enquiries","Read"],["admissions.enquiry.create","Admissions","Enquiries","Create"],["admissions.enquiry.update","Admissions","Enquiries","Update"],["admissions.application.read","Admissions","Applications","Read"],["admissions.application.create","Admissions","Applications","Create"],["admissions.application.approve","Admissions","Applications","Approve"],["admissions.admission.confirm","Admissions","Admissions","Confirm"],
  ["finance.setup.read","Finance","Fee setup","Read"],["finance.setup.manage","Finance","Fee setup","Manage"],["finance.payment.read","Finance","Payments","Read"],["finance.payment.collect","Finance","Payments","Collect"],["finance.payment.void","Finance","Payments","Void incorrect payment"],["finance.payment.refund","Finance","Payments","Refund eligible payment"],["finance.payment-adjustment.read","Finance","Payment adjustments","Read"],["finance.fee-order-recovery.read","Finance","Fee order recovery","Read"],["finance.fee-order-recovery.retry","Finance","Fee order recovery","Retry"],["finance.receipt.read","Finance","Receipts","Read"],["finance.reconciliation.manage","Finance","Reconciliation","Manage"],
] as const;
export const PERMISSION_CATALOG: PermissionCatalogItem[] = PERMISSION_ROWS.map(([code,domain,resource,action])=>({code,domain,resource,action,label:`${resource} ${action.toLowerCase()}`}));
