"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.closeEnquiryUseCase = exports.updateEnquiryUseCase = exports.listEnquiriesUseCase = exports.getEnquiryUseCase = exports.createEnquiryUseCase = void 0;
var create_enquiry_use_case_1 = require("./create-enquiry.use-case");
Object.defineProperty(exports, "createEnquiryUseCase", { enumerable: true, get: function () { return create_enquiry_use_case_1.createEnquiryUseCase; } });
var get_enquiry_use_case_1 = require("./get-enquiry.use-case");
Object.defineProperty(exports, "getEnquiryUseCase", { enumerable: true, get: function () { return get_enquiry_use_case_1.getEnquiryUseCase; } });
var list_enquiries_use_case_1 = require("./list-enquiries.use-case");
Object.defineProperty(exports, "listEnquiriesUseCase", { enumerable: true, get: function () { return list_enquiries_use_case_1.listEnquiriesUseCase; } });
var update_enquiry_use_case_1 = require("./update-enquiry.use-case");
Object.defineProperty(exports, "updateEnquiryUseCase", { enumerable: true, get: function () { return update_enquiry_use_case_1.updateEnquiryUseCase; } });
var close_enquiry_use_case_1 = require("./close-enquiry.use-case");
Object.defineProperty(exports, "closeEnquiryUseCase", { enumerable: true, get: function () { return close_enquiry_use_case_1.closeEnquiryUseCase; } });
