"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.normalizeTenantId = exports.normalizeTenantCode = exports.normalizeTenantClaims = exports.hasTenantHeaders = exports.getTenantSubdomain = exports.getTenantIdFromHeaders = exports.getTenantCodeFromHeaders = exports.resolveTenantFromRequest = exports.requireTenantId = exports.requireTenantCode = exports.requireTenant = exports.hasTenantId = exports.hasTenantCode = exports.getTenantResolutionSource = exports.createTenantContext = void 0;
var context_1 = require("./context");
Object.defineProperty(exports, "createTenantContext", { enumerable: true, get: function () { return context_1.createTenantContext; } });
Object.defineProperty(exports, "getTenantResolutionSource", { enumerable: true, get: function () { return context_1.getTenantResolutionSource; } });
Object.defineProperty(exports, "hasTenantCode", { enumerable: true, get: function () { return context_1.hasTenantCode; } });
Object.defineProperty(exports, "hasTenantId", { enumerable: true, get: function () { return context_1.hasTenantId; } });
Object.defineProperty(exports, "requireTenant", { enumerable: true, get: function () { return context_1.requireTenant; } });
Object.defineProperty(exports, "requireTenantCode", { enumerable: true, get: function () { return context_1.requireTenantCode; } });
Object.defineProperty(exports, "requireTenantId", { enumerable: true, get: function () { return context_1.requireTenantId; } });
Object.defineProperty(exports, "resolveTenantFromRequest", { enumerable: true, get: function () { return context_1.resolveTenantFromRequest; } });
var helpers_1 = require("./helpers");
Object.defineProperty(exports, "getTenantCodeFromHeaders", { enumerable: true, get: function () { return helpers_1.getTenantCodeFromHeaders; } });
Object.defineProperty(exports, "getTenantIdFromHeaders", { enumerable: true, get: function () { return helpers_1.getTenantIdFromHeaders; } });
Object.defineProperty(exports, "getTenantSubdomain", { enumerable: true, get: function () { return helpers_1.getTenantSubdomain; } });
Object.defineProperty(exports, "hasTenantHeaders", { enumerable: true, get: function () { return helpers_1.hasTenantHeaders; } });
Object.defineProperty(exports, "normalizeTenantClaims", { enumerable: true, get: function () { return helpers_1.normalizeTenantClaims; } });
Object.defineProperty(exports, "normalizeTenantCode", { enumerable: true, get: function () { return helpers_1.normalizeTenantCode; } });
Object.defineProperty(exports, "normalizeTenantId", { enumerable: true, get: function () { return helpers_1.normalizeTenantId; } });
