import { ValidationError } from "@school-erp/errors";
import { validateEmail,validateNonEmptyString,validatePhone } from "@school-erp/validation";
import type { EmployeeCreateInput,EmployeeListFilter,EmployeeLoginStatus,EmployeeSortDirection,EmployeeSortField,EmployeeStatus,EmployeeUpdateInput,EmploymentType,StaffCategory,StaffType } from "./employees.model";
const categories:StaffCategory[]=["TEACHING","NON_TEACHING"],employmentTypes:EmploymentType[]=["FULL_TIME","PART_TIME","CONTRACT","VISITING"],staffTypes:StaffType[]=["PRINCIPAL","VICE_PRINCIPAL","DEAN","HOD","TEACHER","LECTURER","LAB_FACULTY","ADMIN_STAFF","SUPPORT_STAFF","OTHER"];
const string=(v:unknown)=>typeof v==="string"&&v.trim()?v.trim():undefined;const strings=(v:unknown)=>Array.isArray(v)?[...new Set(v.map(string).filter((x):x is string=>Boolean(x)))]:[];
export function validateEmployeeCreate(input:unknown):EmployeeCreateInput{if(!input||typeof input!=="object"||Array.isArray(input))throw new ValidationError([{field:"input",message:"input is required"}]);const v=input as Record<string,unknown>,errors:Array<{field:string;message:string}>=[];const name=validateNonEmptyString(v.fullName,"fullName");if(!name.success)errors.push({field:"fullName",message:"full name is required"});const staffCategory=String(v.staffCategory??"") as StaffCategory,staffType=String(v.staffType??"") as StaffType,employmentType=String(v.employmentType??"FULL_TIME") as EmploymentType;if(!categories.includes(staffCategory))errors.push({field:"staffCategory",message:"staff category is invalid"});if(!staffTypes.includes(staffType))errors.push({field:"staffType",message:"staff type is invalid"});if(!employmentTypes.includes(employmentType))errors.push({field:"employmentType",message:"employment type is invalid"});const primaryCampusId=string(v.primaryCampusId),campusIds=strings(v.campusIds);if(!primaryCampusId)errors.push({field:"primaryCampusId",message:"primary campus is required"});if(primaryCampusId&&!campusIds.includes(primaryCampusId))campusIds.unshift(primaryCampusId);const loginEnabled=v.loginEnabled===true;let email=string(v.email);if(email){const checked=validateEmail(email,"email");if(!checked.success)errors.push({field:"email",message:"email is invalid"});else email=checked.value;}if(loginEnabled&&!email)errors.push({field:"email",message:"email is required when login is enabled"});const roleIds=strings(v.roleIds);if(loginEnabled&&!roleIds.length)errors.push({field:"roleIds",message:"at least one role is required when login is enabled"});const joiningDate=v.joiningDate instanceof Date?v.joiningDate:new Date(String(v.joiningDate??new Date().toISOString()));if(Number.isNaN(joiningDate.getTime()))errors.push({field:"joiningDate",message:"joining date is invalid"});const scopeType=String(v.scopeType??"CAMPUS") as "TENANT"|"CAMPUS";if(!["TENANT","CAMPUS"].includes(scopeType))errors.push({field:"scopeType",message:"scope is invalid"});if(errors.length)throw new ValidationError(errors);return{fullName:name.success?name.value:"",...(email?{email}:{}),...(string(v.phone)?{phone:string(v.phone)}:{}),staffCategory,staffType,employmentType,...(string(v.designation)?{designation:string(v.designation)}:{}),...(string(v.department)?{department:string(v.department)}:{}),primaryCampusId:primaryCampusId!,campusIds,joiningDate,loginEnabled,roleIds,scopeType,...(string(v.externalHrCode)?{externalHrCode:string(v.externalHrCode)}:{}),...(string(v.profilePhotoFileId)?{profilePhotoFileId:string(v.profilePhotoFileId)}:{}),...(string(v.templateId)?{templateId:string(v.templateId)}:{}),...(typeof v.templateVersion==="number"?{templateVersion:v.templateVersion}:{}),...(v.customFields&&typeof v.customFields==="object"&&!Array.isArray(v.customFields)?{customFields:v.customFields as Record<string,unknown>}:{})};}
export function validateEmployeeFilter(input:unknown):EmployeeListFilter{const v=input&&typeof input==="object"&&!Array.isArray(input)?input as Record<string,unknown>:{};const status=string(v.status) as EmployeeStatus|undefined,loginStatus=string(v.loginStatus) as EmployeeLoginStatus|undefined,staffCategory=string(v.staffCategory) as StaffCategory|undefined;const page=Number(v.page??1),pageSize=Number(v.pageSize??20),sortBy=String(v.sortBy??"fullName") as EmployeeSortField,sortDirection=String(v.sortDirection??"ASC").toUpperCase() as EmployeeSortDirection;const errors:Array<{field:string;message:string}>=[];if(!Number.isSafeInteger(page)||page<1)errors.push({field:"page",message:"page must be a positive integer"});if(!Number.isSafeInteger(pageSize)||pageSize<1||pageSize>100)errors.push({field:"pageSize",message:"pageSize must be between 1 and 100"});if(!["fullName","employeeCode","joiningDate","createdAt"].includes(sortBy))errors.push({field:"sortBy",message:"sortBy is invalid"});if(!["ASC","DESC"].includes(sortDirection))errors.push({field:"sortDirection",message:"sortDirection is invalid"});if(errors.length)throw new ValidationError(errors);return{...(string(v.search)?{search:string(v.search)}:{}),...(status&&["ACTIVE","INACTIVE","ENDED"].includes(status)?{status}:{}),...(loginStatus&&["NONE","INVITED","ACTIVE","DISABLED","FAILED"].includes(loginStatus)?{loginStatus}:{}),...(staffCategory&&categories.includes(staffCategory)?{staffCategory}:{}),...(string(v.campusId)?{campusId:string(v.campusId)}:{}),page,pageSize,sortBy,sortDirection};}

export function validateEmployeeUpdate(input:unknown):EmployeeUpdateInput{
  if(!input||typeof input!=="object"||Array.isArray(input))throw new ValidationError([{field:"input",message:"input is required"}]);
  const v=input as Record<string,unknown>,update:EmployeeUpdateInput={},errors:Array<{field:string;message:string}>=[];
  if("fullName" in v){const checked=validateNonEmptyString(v.fullName,"fullName");if(!checked.success)errors.push({field:"fullName",message:"full name is required"});else update.fullName=checked.value;}
  if("phone" in v){if(v.phone===null||v.phone==="")update.phone=undefined;else{const checked=validatePhone(v.phone,"phone");if(!checked.success)errors.push({field:"phone",message:checked.errors[0]??"phone is invalid"});else update.phone=checked.value;}}
  for(const key of ["designation","department","externalHrCode","profilePhotoFileId"] as const)if(key in v)update[key]=string(v[key]);
  if("customFields" in v){if(!v.customFields||typeof v.customFields!=="object"||Array.isArray(v.customFields))errors.push({field:"customFields",message:"customFields must be an object"});else update.customFields=v.customFields as Record<string,unknown>;}
  if("staffCategory" in v){const value=String(v.staffCategory) as StaffCategory;if(!categories.includes(value))errors.push({field:"staffCategory",message:"staff category is invalid"});else update.staffCategory=value;}
  if("staffType" in v){const value=String(v.staffType) as StaffType;if(!staffTypes.includes(value))errors.push({field:"staffType",message:"staff type is invalid"});else update.staffType=value;}
  if("employmentType" in v){const value=String(v.employmentType) as EmploymentType;if(!employmentTypes.includes(value))errors.push({field:"employmentType",message:"employment type is invalid"});else update.employmentType=value;}
  if("joiningDate" in v){const value=v.joiningDate instanceof Date?v.joiningDate:new Date(String(v.joiningDate));if(Number.isNaN(value.getTime()))errors.push({field:"joiningDate",message:"joining date is invalid"});else update.joiningDate=value;}
  if("campusIds" in v){const campusIds=strings(v.campusIds);if(!campusIds.length)errors.push({field:"campusIds",message:"at least one campus is required"});else update.campusIds=campusIds;}
  if("primaryCampusId" in v){const primaryCampusId=string(v.primaryCampusId);if(!primaryCampusId)errors.push({field:"primaryCampusId",message:"primary campus is required"});else update.primaryCampusId=primaryCampusId;}
  if(update.campusIds&&update.primaryCampusId&&!update.campusIds.includes(update.primaryCampusId))errors.push({field:"primaryCampusId",message:"primary campus must be included in campus access"});
  if(!Object.keys(update).length&&!errors.length)errors.push({field:"input",message:"at least one editable field is required"});
  if(errors.length)throw new ValidationError(errors);
  return update;
}
