"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateCampusUseCase = exports.listCampusesUseCase = exports.getCampusUseCase = exports.deactivateCampusUseCase = exports.createCampusUseCase = void 0;
var create_campus_use_case_1 = require("./create-campus.use-case");
Object.defineProperty(exports, "createCampusUseCase", { enumerable: true, get: function () { return create_campus_use_case_1.createCampusUseCase; } });
var deactivate_campus_use_case_1 = require("./deactivate-campus.use-case");
Object.defineProperty(exports, "deactivateCampusUseCase", { enumerable: true, get: function () { return deactivate_campus_use_case_1.deactivateCampusUseCase; } });
var get_campus_use_case_1 = require("./get-campus.use-case");
Object.defineProperty(exports, "getCampusUseCase", { enumerable: true, get: function () { return get_campus_use_case_1.getCampusUseCase; } });
var list_campuses_use_case_1 = require("./list-campuses.use-case");
Object.defineProperty(exports, "listCampusesUseCase", { enumerable: true, get: function () { return list_campuses_use_case_1.listCampusesUseCase; } });
var update_campus_use_case_1 = require("./update-campus.use-case");
Object.defineProperty(exports, "updateCampusUseCase", { enumerable: true, get: function () { return update_campus_use_case_1.updateCampusUseCase; } });
