import { BadRequestError, ConflictError } from "@school-erp/errors";
import { createMongoCollectionAdapter,getCollection,type CollectionAdapter,type MongoEnvLike } from "@school-erp/mongodb";
import type { CampusTransferPage,CampusTransferPageFilter,CampusTransferRecord,CampusTransferStatus } from "./campus-transfers.model";
interface Document extends Record<string,unknown>{_id:string;tenantId:string;record:CampusTransferRecord}
const clone=(record:CampusTransferRecord):CampusTransferRecord=>{const copy={...record,source:{...record.source},target:{...record.target},effectiveAt:new Date(record.effectiveAt),createdAt:new Date(record.createdAt),updatedAt:new Date(record.updatedAt),history:record.history.map(item=>({...item,at:new Date(item.at)}))};if(record.completedAt)return{...copy,completedAt:new Date(record.completedAt)};delete(copy as Partial<CampusTransferRecord>).completedAt;return copy};
export interface CampusTransferRepository{create(record:CampusTransferRecord):Promise<CampusTransferRecord>;getById(tenantId:string,id:string):Promise<CampusTransferRecord|null>;getByRequestId(tenantId:string,clientRequestId:string):Promise<CampusTransferRecord|null>;getActiveByStudent(tenantId:string,studentId:string):Promise<CampusTransferRecord|null>;listByStudent(tenantId:string,studentId:string):Promise<CampusTransferRecord[]>;listPage(tenantId:string,filter?:CampusTransferPageFilter):Promise<CampusTransferPage>;update(tenantId:string,id:string,input:Partial<CampusTransferRecord>,expectedStatuses?:CampusTransferStatus[]):Promise<CampusTransferRecord>}
export class InMemoryCampusTransferRepository implements CampusTransferRepository{
  private records=new Map<string,CampusTransferRecord>();
  async create(record:CampusTransferRecord){if(await this.getByRequestId(record.tenantId,record.clientRequestId))throw new ConflictError("campus transfer request already exists");this.records.set(record.id,clone(record));return clone(record)}
  async getById(tenantId:string,id:string){const value=this.records.get(id);return value?.tenantId===tenantId?clone(value):null}
  async getByRequestId(tenantId:string,key:string){const value=[...this.records.values()].find(item=>item.tenantId===tenantId&&item.clientRequestId===key);return value?clone(value):null}
  async getActiveByStudent(tenantId:string,studentId:string){const value=[...this.records.values()].find(item=>item.tenantId===tenantId&&item.studentId===studentId&&["DRAFT","UNDER_REVIEW","PROCESSING"].includes(item.status));return value?clone(value):null}
  async listByStudent(tenantId:string,studentId:string){return[...this.records.values()].filter(item=>item.tenantId===tenantId&&item.studentId===studentId).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()).map(clone)}
  async listPage(tenantId:string,filter:CampusTransferPageFilter={}){const search=filter.search?.trim().toLowerCase();const rows=[...this.records.values()].filter(item=>item.tenantId===tenantId&&(!filter.status||item.status===filter.status)&&(!search||item.studentName.toLowerCase().includes(search)||item.registrationNumber.toLowerCase().includes(search)||item.targetRegistrationNumber.toLowerCase().includes(search))).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime());const page=Math.max(1,filter.page??1),pageSize=Math.min(100,Math.max(1,filter.pageSize??20)),total=rows.length;return{items:rows.slice((page-1)*pageSize,page*pageSize).map(clone),page,pageSize,total,totalPages:Math.ceil(total/pageSize)}}
  async update(tenantId:string,id:string,input:Partial<CampusTransferRecord>,expected?:CampusTransferStatus[]){const current=await this.getById(tenantId,id);if(!current)throw new BadRequestError("campus transfer was not found");if(expected&&!expected.includes(current.status))throw new ConflictError(`campus transfer cannot change from ${current.status}`);const next=clone({...current,...input,id:current.id,tenantId:current.tenantId});this.records.set(id,next);return clone(next)}
}
class MongoCampusTransferRepository implements CampusTransferRepository{
  constructor(private collection:CollectionAdapter<Document>){}
  private from(document:Document|null){return document?clone(document.record):null}
  async create(record:CampusTransferRecord){await this.collection.insertOne({_id:record.id,tenantId:record.tenantId,record:clone(record)});return clone(record)}
  async getById(tenantId:string,id:string){return this.from(await this.collection.findOne({tenantId,_id:id}))}
  async getByRequestId(tenantId:string,key:string){return this.from(await this.collection.findOne({tenantId,"record.clientRequestId":key}as never))}
  async getActiveByStudent(tenantId:string,studentId:string){return this.from(await this.collection.findOne({tenantId,"record.studentId":studentId,"record.status":{$in:["DRAFT","UNDER_REVIEW","PROCESSING"]}}as never))}
  async listByStudent(tenantId:string,studentId:string){return(await this.collection.findMany({tenantId,"record.studentId":studentId}as never,{sort:{"record.createdAt":-1}})).map(item=>clone(item.record))}
  async listPage(tenantId:string,filter:CampusTransferPageFilter={}){const query:Record<string,unknown>={tenantId};if(filter.status)query["record.status"]=filter.status;if(filter.search?.trim()){const expression={$regex:filter.search.trim().replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),$options:"i"};query.$or=[{"record.studentName":expression},{"record.registrationNumber":expression},{"record.targetRegistrationNumber":expression}]}const page=Math.max(1,filter.page??1),pageSize=Math.min(100,Math.max(1,filter.pageSize??20));const[rows,total]=await Promise.all([this.collection.findMany(query as never,{sort:{"record.createdAt":-1},skip:(page-1)*pageSize,limit:pageSize}),this.collection.count(query as never)]);return{items:rows.map(item=>clone(item.record)),page,pageSize,total,totalPages:Math.ceil(total/pageSize)}}
  async update(tenantId:string,id:string,input:Partial<CampusTransferRecord>,expected?:CampusTransferStatus[]){const filter:Record<string,unknown>={tenantId,_id:id};if(expected)filter["record.status"]={$in:expected};const current=await this.collection.findOne({tenantId,_id:id});if(!current)throw new BadRequestError("campus transfer was not found");const next=clone({...current.record,...input,id:current.record.id,tenantId:current.record.tenantId});const replaced=await this.collection.replaceOne(filter as never,{_id:id,tenantId,record:next});if(!replaced)throw new ConflictError(`campus transfer cannot change from ${current.record.status}`);return clone(next)}
}
function env():MongoEnvLike{return(globalThis as unknown as{process?:{env?:MongoEnvLike}}).process?.env??{}}
let singleton:Promise<CampusTransferRepository>|undefined;
export async function createCampusTransferRepository(environment:MongoEnvLike=env()){if(!environment.MONGODB_URI&&!environment.MONGODB_URI_DEV&&!environment.MONGODB_URI_PROD&&!environment.MONGODB_URI_TEST)return new InMemoryCampusTransferRepository();const native=await getCollection<Document>("academic_campus_transfers",environment);await native.createIndex({tenantId:1,"record.clientRequestId":1},{unique:true});await native.createIndex({tenantId:1,"record.studentId":1,"record.createdAt":-1});await native.createIndex({tenantId:1,"record.studentId":1,"record.status":1});return new MongoCampusTransferRepository(createMongoCollectionAdapter(native))}
export function campusTransferRepository(){singleton??=createCampusTransferRepository();return singleton}
