import test from"node:test";import assert from"node:assert/strict";import{InMemoryEventPublisher}from"@school-erp/events";import type{RequestContext}from"@school-erp/api";import{InMemoryClassRepository}from"../../classes/classes.repository";import{InMemorySectionRepository}from"../../sections/sections.repository";import{InMemoryStudentRepository}from"../students.repository";import{changeStudentEnrollment,createStudentFromAdmission,getStudentByAdmissionApplicationId}from"../students.service";
const input={admissionApplicationId:"application_1",admissionNumber:"ADM/26-27/0001",campusId:"campus_1",academicYearId:"year_2026",classId:"class_1",studentName:"Aarav Sharma",phone:"9876543210",parentName:"Meera Sharma",confirmedBy:"admission_officer_1",confirmedAt:"2026-06-01T10:00:00.000Z"};
async function dependencies(){const classes=new InMemoryClassRepository(),sections=new InMemorySectionRepository();await classes.create("tenant_one",{campusId:"campus_1",programId:"program_1",name:"Class 10",code:"CLASS-010"});await classes.create("tenant_one",{campusId:"campus_1",programId:"program_1",name:"Class 11",code:"CLASS-011"});const academicClass=await classes.getByCode("tenant_one","campus_1","CLASS-010"),nextClass=await classes.getByCode("tenant_one","campus_1","CLASS-011");await sections.create("tenant_one",{campusId:"campus_1",programId:"program_1",classId:nextClass!.id,name:"Section A",code:"SEC-001"});const section=await sections.getByCode("tenant_one","campus_1","SEC-001");return{repository:new InMemoryStudentRepository(),classes,sections,academicClass,nextClass,section};}
const context=():RequestContext=>({requestId:"request_1",method:"POST",path:"graphql:changeStudentEnrollment",headers:{},query:{},body:{},params:{},tenantContext:{tenantId:"tenant_one",source:"jwt-claims",resolvedAt:new Date()},authContext:{source:"jwt-claims",authenticatedAt:new Date(),user:{id:"admin_1",permissions:["academics.enrollment.create","academics.student.read"],source:"jwt-claims"}}});
test("creates one authoritative student and enrollment from admission",async()=>{const deps=await dependencies();const result=await createStudentFromAdmission({...input,classId:deps.academicClass!.id},"tenant_one",deps);assert.equal(result.name,"Aarav Sharma");assert.equal(result.enrollment.programId,"program_1");assert.equal(result.enrollment.classId,deps.academicClass!.id);});
test("retries are idempotent by admission application",async()=>{const deps=await dependencies();const command={...input,classId:deps.academicClass!.id};const first=await createStudentFromAdmission(command,"tenant_one",deps);const second=await createStudentFromAdmission(command,"tenant_one",deps);assert.equal(second.id,first.id);assert.equal(second.enrollment.id,first.enrollment.id);assert.equal(second.registrationNumber,first.registrationNumber);});
test("resolves the authoritative student from an admitted application",async()=>{const deps=await dependencies();const created=await createStudentFromAdmission({...input,classId:deps.academicClass!.id},"tenant_one",deps);const resolved=await getStudentByAdmissionApplicationId(input.admissionApplicationId,context(),deps);assert.equal(resolved.id,created.id);assert.equal(resolved.admissionApplicationId,input.admissionApplicationId);});
test("rejects a class from another campus",async()=>{const deps=await dependencies();await assert.rejects(()=>createStudentFromAdmission({...input,campusId:"campus_two",classId:deps.academicClass!.id},"tenant_one",deps),/does not belong/);});
test("student repository paginates deterministically after tenant and enrollment filters",async()=>{const deps=await dependencies();for(let index=0;index<4;index+=1)await createStudentFromAdmission({...input,admissionApplicationId:`application_${index}`,admissionNumber:`ADM/26-27/00${index+1}`,studentName:["Diya Rao","Aarav Rao","Kavya Rao","Ishaan Rao"][index]!,phone:`98765432${10+index}`,classId:deps.academicClass!.id},"tenant_one",deps);const first=await deps.repository.list("tenant_one",{campusId:"campus_1",limit:2,offset:0}),second=await deps.repository.list("tenant_one",{campusId:"campus_1",limit:2,offset:2});assert.equal(first.length,2);assert.equal(second.length,2);assert.equal(first[0]?.student.name,"Aarav Rao");assert.equal(second[0]?.student.name,"Ishaan Rao");});
test("student page returns server metadata and deterministic sorting",async()=>{const deps=await dependencies();for(let index=0;index<4;index+=1)await createStudentFromAdmission({...input,admissionApplicationId:`page_application_${index}`,admissionNumber:`ADM/26-27/10${index+1}`,studentName:["Diya Rao","Aarav Rao","Kavya Rao","Ishaan Rao"][index]!,phone:`98765000${10+index}`,classId:deps.academicClass!.id},"tenant_one",deps);const result=await deps.repository.listPage("tenant_one",{campusId:"campus_1",page:2,pageSize:2,sortBy:"name",sortDirection:"ASC"});assert.equal(result.total,4);assert.equal(result.totalPages,2);assert.equal(result.page,2);assert.equal(result.items[0]?.student.name,"Ishaan Rao");});
test("changes enrollment with history and publishes the fee-assignment event",async()=>{const deps=await dependencies(),publisher=new InMemoryEventPublisher();const student=await createStudentFromAdmission({...input,classId:deps.academicClass!.id},"tenant_one",deps);const changed=await changeStudentEnrollment(student.id,{campusId:"campus_1",academicYearId:"year_2026",classId:deps.nextClass!.id,sectionId:deps.section!.id,rollNumber:"11-A-001",reason:"Promoted after annual review"},context(),{...deps,publisher});assert.notEqual(changed.enrollment.id,student.enrollment.id);assert.equal(changed.enrollment.classId,deps.nextClass!.id);assert.equal(changed.enrollment.sectionId,deps.section!.id);assert.equal(publisher.events[0]?.type,"academics.student.enrollment-changed.v1");assert.equal((publisher.events[0]?.data as{previousEnrollmentId:string}).previousEnrollmentId,student.enrollment.id);});
test("rejects a section that does not belong to the selected class",async()=>{const deps=await dependencies(),student=await createStudentFromAdmission({...input,classId:deps.academicClass!.id},"tenant_one",deps);await assert.rejects(()=>changeStudentEnrollment(student.id,{campusId:"campus_1",academicYearId:"year_2026",classId:deps.academicClass!.id,sectionId:deps.section!.id,reason:"Correction"},context(),{...deps,publisher:new InMemoryEventPublisher()}),/section does not belong/);});
