import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getMongoConnection, type MongoEnvLike } from "@school-erp/mongodb";
export interface StudentDocumentBranding { institutionName:string; shortName?:string; address?:string; contactPhone?:string; contactEmail?:string; campusName:string; academicYearName:string; className:string; sectionName?:string; logoBytes?:Uint8Array; logoContentType?:string }
interface NamedAcademicDocument { _id:string; tenantId:string; name?:unknown }
export async function getStudentDocumentBranding(tenantId:string,campusId:string,academicYearId:string,classId:string,sectionId?:string):Promise<StudentDocumentBranding>{
  const env=(globalThis as unknown as {process?:{env?:MongoEnvLike}}).process?.env??{};const connection=await getMongoConnection(env);const stage=env.environment??env.STAGE??env.NODE_ENV??"dev";const settings=connection.client.db(`settings-service_${stage}`);const academics=connection.client.db(connection.dbName);const storage=connection.client.db(`storage-service_${stage}`);
  const [profile,campus,year,academicClass,section]=await Promise.all([settings.collection("settings_institution_profiles").findOne({tenantId}),settings.collection("settings_campuses").findOne({tenantId,id:campusId}),settings.collection("settings_academic_years").findOne({tenantId,id:academicYearId}),academics.collection<NamedAcademicDocument>("academics_classes").findOne({tenantId,_id:classId}),sectionId?academics.collection<NamedAcademicDocument>("academics_sections").findOne({tenantId,_id:sectionId}):null]);
  const result:StudentDocumentBranding={institutionName:String(profile?.name??"Institution"),campusName:String(campus?.name??"Campus"),academicYearName:String(year?.name??year?.code??"Academic year"),className:String(academicClass?.name??"Class")};
  if(typeof profile?.shortName==="string")result.shortName=profile.shortName;if(typeof profile?.address==="string")result.address=profile.address;if(typeof profile?.contactPhone==="string")result.contactPhone=profile.contactPhone;if(typeof profile?.contactEmail==="string")result.contactEmail=profile.contactEmail;if(typeof section?.name==="string")result.sectionName=section.name;
  if(typeof profile?.logoFileId==="string"){const file=await storage.collection("storage_files").findOne({tenantId,id:profile.logoFileId,status:"AVAILABLE"});if(file&&typeof file.bucket==="string"&&typeof file.storageKey==="string"){const object=await new S3Client({}).send(new GetObjectCommand({Bucket:file.bucket,Key:file.storageKey}));if(object.Body){result.logoBytes=await object.Body.transformToByteArray();const contentType=typeof file.contentType==="string"?file.contentType:object.ContentType;if(contentType)result.logoContentType=contentType;}}}
  return result;
}
