import type { RequestContext } from "@school-erp/api";
import type { Permission } from "@school-erp/auth";
import { BadRequestError, ForbiddenError, NotFoundError } from "@school-erp/errors";
import { academicsPermissions } from "../../permissions";
import { studentRepository, type StudentRepository } from "../students/students.repository";
import type { IssueStudentDocumentInput, StudentDocumentFilter, StudentDocumentRecord, StudentDocumentType } from "./student-documents.model";
import { studentDocumentRepository, type StudentDocumentRepository } from "./student-documents.repository";
export interface StudentDocumentDeps { repository?: StudentDocumentRepository|Promise<StudentDocumentRepository>; students?: StudentRepository|Promise<StudentRepository>; now?:()=>Date }
const req=(value:unknown,field:string)=>{if(typeof value!=="string"||!value.trim())throw new BadRequestError(`${field} is required`);return value.trim()};
const tenant=(ctx:RequestContext)=>req(ctx.tenantContext?.tenantId,"tenantId");const actor=(ctx:RequestContext)=>req(ctx.authContext?.user?.id,"userId");
const permit=(ctx:RequestContext,p:Permission)=>{if(!(ctx.authContext?.user?.permissions??[]).includes(p))throw new ForbiddenError(`permission ${p} is required`)};
const repo=async(d?:StudentDocumentDeps)=>await(d?.repository??studentDocumentRepository());const students=async(d?:StudentDocumentDeps)=>await(d?.students??studentRepository());
const view=(r:StudentDocumentRecord)=>({...r,issuedAt:r.issuedAt.toISOString(),updatedAt:r.updatedAt.toISOString(),validUntil:r.validUntil?.toISOString(),revokedAt:r.revokedAt?.toISOString()});
function validate(input:unknown):IssueStudentDocumentInput{if(!input||typeof input!=="object"||Array.isArray(input))throw new BadRequestError("input is required");const value=input as Record<string,unknown>;const documentType=req(value.documentType,"documentType") as StudentDocumentType;if(!["BONAFIDE_CERTIFICATE","STUDY_CERTIFICATE","TRANSFER_CERTIFICATE","STUDENT_ID_CARD"].includes(documentType))throw new BadRequestError("documentType is invalid");const purpose=typeof value.purpose==="string"&&value.purpose.trim()?value.purpose.trim():undefined;const validUntil=typeof value.validUntil==="string"&&value.validUntil.trim()?value.validUntil.trim():undefined;return{studentId:req(value.studentId,"studentId"),documentType,...(purpose?{purpose}:{}),...(validUntil?{validUntil}:{})};}
export async function issueStudentDocument(input:unknown,ctx:RequestContext,deps?:StudentDocumentDeps){permit(ctx,academicsPermissions.studentDocuments.issue as Permission);const parsed=validate(input),tid=tenant(ctx),student=await(await students(deps)).getById(tid,parsed.studentId);if(!student)throw new NotFoundError("student not found");const at=deps?.now?.()??new Date();const repository=await repo(deps);const record:StudentDocumentRecord={id:`student_document_${crypto.randomUUID()}`,tenantId:tid,documentNumber:await repository.nextNumber(tid,parsed.documentType,at.getUTCFullYear(),student.enrollment.campusId,student.enrollment.academicYearId),documentType:parsed.documentType,studentId:student.student.id,studentName:student.student.name,admissionNumber:student.student.admissionNumber,registrationNumber:student.student.registrationNumber,campusId:student.enrollment.campusId,academicYearId:student.enrollment.academicYearId,classId:student.enrollment.classId,...(student.enrollment.sectionId?{sectionId:student.enrollment.sectionId}:{}),...(parsed.purpose?{purpose:parsed.purpose}:{}),...(parsed.validUntil?{validUntil:new Date(parsed.validUntil)}:{}),status:"ISSUED",issuedBy:actor(ctx),issuedAt:at,updatedAt:at};return view(await repository.create(record));}
export async function listStudentDocuments(filter:unknown,ctx:RequestContext,deps?:StudentDocumentDeps){permit(ctx,academicsPermissions.studentDocuments.read as Permission);const value=filter&&typeof filter==="object"&&!Array.isArray(filter)?filter as Record<string,unknown>:{};const parsed:StudentDocumentFilter={};for(const field of ["studentId","campusId","academicYearId","documentType","status"] as const)if(typeof value[field]==="string"&&value[field].trim())Object.assign(parsed,{[field]:value[field].trim()});return(await(await repo(deps)).list(tenant(ctx),parsed)).map(view);}
export async function getStudentDocument(id:string,ctx:RequestContext,deps?:StudentDocumentDeps){permit(ctx,academicsPermissions.studentDocuments.read as Permission);const record=await(await repo(deps)).getById(tenant(ctx),req(id,"id"));if(!record)throw new NotFoundError("student document not found");return view(record);}
export async function revokeStudentDocument(id:string,reason:string,ctx:RequestContext,deps?:StudentDocumentDeps){permit(ctx,academicsPermissions.studentDocuments.revoke as Permission);const record=await(await repo(deps)).revoke(tenant(ctx),req(id,"id"),actor(ctx),req(reason,"reason"));if(!record)throw new NotFoundError("issued student document not found");return view(record);}
