"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.verifyCognitoJwtPlaceholder = exports.resolveAuthFromRequest = exports.requirePermission = exports.requireAuth = exports.hasPermission = exports.normalizePermissions = exports.normalizePermission = exports.normalizeAuthClaims = exports.getUserRoleFromHeaders = exports.getUserPermissionsFromHeaders = exports.getUserIdFromHeaders = exports.getUserEmailFromHeaders = exports.ensurePermissionFormat = exports.buildTenantContext = exports.buildAuthUser = void 0;
var helpers_1 = require("./helpers");
Object.defineProperty(exports, "buildAuthUser", { enumerable: true, get: function () { return helpers_1.buildAuthUser; } });
Object.defineProperty(exports, "buildTenantContext", { enumerable: true, get: function () { return helpers_1.buildTenantContext; } });
Object.defineProperty(exports, "ensurePermissionFormat", { enumerable: true, get: function () { return helpers_1.ensurePermissionFormat; } });
Object.defineProperty(exports, "getUserEmailFromHeaders", { enumerable: true, get: function () { return helpers_1.getUserEmailFromHeaders; } });
Object.defineProperty(exports, "getUserIdFromHeaders", { enumerable: true, get: function () { return helpers_1.getUserIdFromHeaders; } });
Object.defineProperty(exports, "getUserPermissionsFromHeaders", { enumerable: true, get: function () { return helpers_1.getUserPermissionsFromHeaders; } });
Object.defineProperty(exports, "getUserRoleFromHeaders", { enumerable: true, get: function () { return helpers_1.getUserRoleFromHeaders; } });
Object.defineProperty(exports, "normalizeAuthClaims", { enumerable: true, get: function () { return helpers_1.normalizeAuthClaims; } });
Object.defineProperty(exports, "normalizePermission", { enumerable: true, get: function () { return helpers_1.normalizePermission; } });
Object.defineProperty(exports, "normalizePermissions", { enumerable: true, get: function () { return helpers_1.normalizePermissions; } });
var auth_1 = require("./auth");
Object.defineProperty(exports, "hasPermission", { enumerable: true, get: function () { return auth_1.hasPermission; } });
Object.defineProperty(exports, "requireAuth", { enumerable: true, get: function () { return auth_1.requireAuth; } });
Object.defineProperty(exports, "requirePermission", { enumerable: true, get: function () { return auth_1.requirePermission; } });
Object.defineProperty(exports, "resolveAuthFromRequest", { enumerable: true, get: function () { return auth_1.resolveAuthFromRequest; } });
var jwt_placeholder_1 = require("./jwt-placeholder");
Object.defineProperty(exports, "verifyCognitoJwtPlaceholder", { enumerable: true, get: function () { return jwt_placeholder_1.verifyCognitoJwtPlaceholder; } });
